### ISSUE TITLE
{{magento_bin}} ignores deployers {{bin/php}} setting

### ISSUE THREAD

**Issue by renttek** [jalogut/magento2-deployer-plus#2]
Hi,

I was playing around with this project and ran into some errors on build machines with multiple versions of php installed. 

TL;DR: {{magento_bin}} ignores deployers {{bin/php}} setting and executes the wrong php binary

The {{magento_bin}} command just executes the <root>/bin/magneot command, which in turn uses the env command in the shebang to determine which php executable to use 
(#!/usr/bin/env php)

In deployer it is possible to set another php executable with set('bin/php', ...) like this:
```php
set('bin/php', function () {
    return locateBinaryPath('php7.1');
});
```

The easiest fix would be to use "{{bin/php}}" to execute bin/magento.

To do this, in file recipe/magento_2_1.php change Line 27:

From:
```php
set('magento_bin', '{{bin/php}} {{magento_dir}}/bin/magento');
```
To:
```php
set('magento_bin', '{{magento_dir}}/bin/magento');
```

**Comment by jalogut** [comment]
@renttek thanks again. See my comment in the PR #3
