### ISSUE TITLE
"var/cache" cannot be deleted 

### ISSUE THREAD

**Issue by superdav42** [jalogut/magento2-deployer-plus#20]
Just got this error on a running production server when trying to load any page.
Fatal error: Uncaught Magento\Framework\Exception\FileSystemException: The directory "/srv/releases/20180723163849/var/cache" cannot be deleted Warning!rmdir(/srv/releases/20180723163849/var/cache): Not a directory in /srv/releases/20180723163849/vendor/magento/framework/Filesystem/Driver/File.php:410 Stack trace: #0 /srv/releases/20180723163849/vendor/magento/framework/Filesystem/Directory/Write.php(174): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/srv/releases/2...') #1 /srv/releases/20180723163849/vendor/magento/framework/Code/GeneratedFiles.php(97): Magento\Framework\Filesystem\Directory\Write->delete('var/cache') #2 /srv/releases/20180723163849/vendor/magento/framework/App/ObjectManagerFactory.php(110): Magento\Framework\Code\GeneratedFiles->cleanGeneratedFiles() #3 /srv/releases/20180723163849/vendor/magento/framework/App/Bootstrap.php(208): Magento\Framework\App\ObjectManagerFactory->create(Array) #4 /srv/releases/20180723163849/vendor/magento/framework/App/Bootstrap.php(123): Magento\Framework\App\ in /srv/releases/20180723163849/vendor/magento/framework/Filesystem/Driver/File.php on line 410

Something is causing Magento to try to delete the cache folder but it gives up because it's a symlink. The code that triggers this is in magento/framework/Code/GeneratedFiles.php whenever the .regenerate file exists in /var. Not sure what created it but it seem just part of the normal magento operations. 

We may have to do something else with var/cache or modify the code to do rm var/cache/*

**Comment by superdav42** [comment]
Actually I think someone else was directly adding/removing modules on the server which would cause it to try and regenerate var/cache. Although it would be good if the went through the deploy process it would be ideal if doing this wouldn't bring the site down.

**Comment by mage2go** [comment]
I am encountering exactly the same issue. 
`~/magento2$ bin/magento setup:di:compile

In Write.php line 202:

  The directory "/data/web/release_production/releases/20191125192232/var/cache/" cannot be deleted Warning!rmdir(/data/web/release_production/releases/20191125192232/var/cache/): Not a
  directory
`
If i replace the symlink with a real folder it works like expected. Tried to give the folders 777 permissions but to no avail. 
Magento 2.3.2, PHP7.2

**Comment by lfolco** [comment]
Can we reopen this? I am having the same issue.
