### ISSUE TITLE
config:remove-dev-modules local instead of remote

### ISSUE THREAD

**Issue by luukschakenraad** [jalogut/magento2-deployer-plus#23]
I use git-deployment, so Deployer checks out a branch on the remote server. When using `config:remove-dev-modules`, this removes the dev-modules on my local machine which causes two problems:

1. The changed file is never sent to the remote server, so I still get the error `bin/magento setup:db:status` for which this function was designed.
2. In theory I could have checked out a branch in which more or less dev-modules are enabled, so just sending the local file to remote can cause problems.

This is my first time using Deployer, so I don't know what are the possibilities to solve this. I can think of two solutions:

1. `config:remove-dev-modules` should run on the server instead of running locally. Maybe this can be done using a replace with `sed`: `sed -i '/<module>/d' ./app/etc/config.php`

2. Download `deploy.sh` and `./app/etc/config.php` from remote, replace locally and send the replaced document back to remote.

If I can be of any assistance to solve this issue, please let me know.

**Comment by jalogut** [comment]
Hi @luukschakenraad 
Thank you for your report. I have checked the code and you are rigth. The problem is this line:

- 
https://github.com/jalogut/magento2-deployer-plus/blob/master/recipe/magento_2_2/config.php#L59

To run that on the server we could replace that line with something like that instead:

```
$updatedConfig = "<?php\nreturn " . \var_export($config, true) . ";";
run("echo $updatedConfig > $configFile");
```
If echo does not set the right format, could you also try `printf "%s\n" $updatedConfig > $configFile`

Could you test that and let me know if it works?

If we need the sencond one with the `printf` we migth need to do the following instead.

```
set('config_updated_file', "<?php\nreturn " . \var_export($config, true) . ";");
set('config_file', $configFile);
run('printf "%s\n" {{config_updated_file}} > {{config_file}}");
```

**Comment by jalogut** [comment]
Hi @schmengler 

FYI

**Comment by luukschakenraad** [comment]
Thank you for your response @jalogut! Unfortunately the echo does not work:

```
✔ Executing task deploy:unlock

In Client.php line 99:
                                                        
  The command "echo <?php                               
  return array (                                        
    'modules' =>                                        
    array (                                             
      ...                       
    ),                                                  
  ); > ./app/etc/config.php" failed.                    
                                                        
  Exit Code: 2 (Misuse of shell builtins)               
                                                        
  Host Name: test                                       
                                                        
  ================                                      
  bash: line 1: ?php: No such file or directory         
  bash: line 2: syntax error near unexpected token `('  
  bash: line 2: `return array ('   
```

So I tried some other commands and ended up with:

```
        $updatedConfig = "<?php\nreturn " . \var_export($config, true) . ";";
        $updatedConfigEof = "<<-EOF\n".$updatedConfig."\nEOF";
        run("tee {{release_path}}/$configFile $updatedConfigEof");
```

That works as expected.

**Comment by jalogut** [comment]
Great! This wouldn’t work either?

```
run("echo $updatedConfigEof > {{release_path}}/$configFile");
```

For the artifact deployments we could move the following line between lines 39-40.

- https://github.com/jalogut/magento2-deployer-plus/blob/master/recipe/magento_2_2.php#L27

That way both release types do that on the server. What do you think?

**Comment by luukschakenraad** [comment]
Yup, echo works as well! Echo didn't work, switched to tee, kept debugging with tee, never switched back to echo.

I don't think line 27 can be moved in between line 39-40. Line 28 (`files:generate`) would then generate static content with the non-modified config.php. 

Probably it wouldn't really lead to problems because it will generate static files for modules which aren't used, though I think it's better not to move it.

**Comment by jalogut** [comment]
Ok, then let’s better use `echo` for that as it will work for all os systems. Very good point about the artifact deployment. I will try to think about a solution that works on both. Although  I do not have much time now. If you have any suggestion, I would be very glad to get some help with that.

**Comment by jalogut** [comment]
@luukschakenraad what about `set('release_path', '.');` rigth after this line?

- https://github.com/jalogut/magento2-deployer-plus/blob/master/recipe/magento_2_2.php#L21

**Comment by luukschakenraad** [comment]
The echo did not seem to work. I didn't give any errors, but it didn't write content as wel. I now changed it to:

```
        $updatedConfig = "<?php\nreturn " . \var_export($config, true) . ";";
        $updatedConfigEof = "\n".$updatedConfig."\nEOF";
        run("cat <<EOF > {{release_path}}/$configFile $updatedConfigEof");
```

> @luukschakenraad what about `set('release_path', '.');` rigth after this line?
> 
> * https://github.com/jalogut/magento2-deployer-plus/blob/master/recipe/magento_2_2.php#L21

Just tested it and it seems to work! Would be nice though if we can reset the file after the build so it prevents accidentally committing that modified config file.

**Comment by luukschakenraad** [comment]
@jalogut Just updated the module and ran a deploy and build. Everything works as expected. Thank you for your help.

About the build-command; I think you're right. Let's not modify it behaviour for now.

**Comment by jalogut** [comment]
Great! Thanks a lot for your help.
