### ISSUE TITLE
Loss of the contents of folders var and pub

### ISSUE THREAD

**Issue by demidov-i-a** [jalogut/magento2-deployer-plus#26]
When switching to a new release occurs, the contents of folders var and pub are lost with the exception of these shared folders

set ('shared_dirs', [
     '{{magento_dir}}/pub/media',
     '{{magento_dir}}/var/log',
     '{{magento_dir}}/var/backups',
     '{{magento_dir}}/var/session',
]);

The problem is that many modules save files directly to the root of folders var and pub.

For example,
pub/google_sitemap_3_1008.xml

Do I understand correctly that this is the right behavior and can this problem be solved in some way?

**Comment by osrecio** [comment]
Yes,  you can solve the problem adding new folder in shared_dirs. For example:
```
set ('shared_dirs', [
'{{magento_dir}}/pub/media',
'{{magento_dir}}/var/log',
'{{magento_dir}}/var/backups',
'{{magento_dir}}/var/session',
'{{magento_dir}}pub/sitemaps',
]);
```

In your Magento you should add your sitemaps inside of your folder: `sitemaps`

And you shoul hace access to your sitempas like: https://domain.com/sitemaps/google_sitemap_3_1008.xml
And specify in Google Search console this route.

**Comment by demidov-i-a** [comment]
Thanks for the help!
