### ISSUE TITLE
Regarding files:permissions

### ISSUE THREAD

**Issue by erfanimani** [jalogut/magento2-deployer-plus#27]
In recipe/magento_2_1/files.php theres a files:permissions task:

    task(
        'files:permissions',
        'cd {{magento_dir}} && find var vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \; ' .
        '&& find var vendor pub/static pub/media app/etc -type d -exec chmod g+w {} \; && chmod u+x bin/magento'
    );

For both files and directories it's executing `chmod g+w`. I assume this is meant to give directories execute permissions as well? If not, why not just use `chmod -R g+w var vendor ...`, it's much faster.

**Comment by jalogut** [comment]
Hi @erfanimani

Now that you mention it, I guess you are right. I just took the command from the official magento docs and did not really think about it. Could you create a PR?

**Comment by sprankhub** [comment]
This is merged and can be closed, right? :)

**Comment by osrecio** [comment]
Yes, thanks @sprankhub !
