### ISSUE TITLE
OpCache Reset

### ISSUE THREAD

**Issue by sprankhub** [jalogut/magento2-deployer-plus#30]
Since Deployer heavily relies on symlinks and symlinks are cached by the OpCache, a PHP reload or any other OpCache reset command is necessary during the deployment. Currently, this is done via a `sudo` command:

https://github.com/jalogut/magento2-deployer-plus/blob/66d1ee4dbc92e10e3ecc250598d12f9d961f110b/deploy.php.sample_2_2_5#L20

I suggest using the project [CacheTool](https://github.com/gordalina/cachetool) for it, because it does not rely on sudoer rights if I understand correctly.

What do you think?

**Comment by stu177** [comment]
There is a method to allow a system user sudo rights for specific commands however this isn't ideal.

Any solution that works and doesn't require sudo would be a good amendment in my opinion.

**Comment by jalogut** [comment]
Hi @sprankhub

That is exactly the reason why this command is on the sample file and not inside the project task commands. The intention is just to provide an example but you should edit with the command you wish. If you want to do it with the CacheTool, just install it as dependency in your project and edit the command to execute the CacheTool command.

In case that you want to use a sudo command, you can allow a user to run only specific commands as sudo. Exactly as @stu177 mentioned. You can check how to do it in the link below:

* https://www.atrixnet.com/allow-an-unprivileged-user-to-run-a-certain-command-with-sudo/

I hope this clarifies your issue

**Comment by sprankhub** [comment]
Thanks for the additional information! If I understand correctly, the CacheTool should work in any environment. Would you merge a pull request, if I provide a decent one?

**Comment by jalogut** [comment]
Hi, thanks for your proposal but I do not think that is needed. I would prefer not adding and additional dependency. I had some issues installing that tool in the past:

* https://github.com/gordalina/cachetool/issues/48#issuecomment-287346033

So for now I’d leave it like that. As I said, anyone can easily add the dependency on their projects and modify the command if they do not want to use sudo.

**Comment by sprankhub** [comment]
Hmm pity. If it worked correctly, we could add the OpCache clear command to the project task commands, which would be nice. However, if you do not want to add this, we can close this issue. Thanks for the fast feedback!

**Comment by sprankhub** [comment]
FYI I added `deployer/recipes` as a dependency now, required the cachetool file:

    require 'vendor/deployer/recipes/recipe/cachetool.php';

defined when the OpCache clear should be done:

    after('cache:clear', 'cachetool:clear:opcache');

and configured the cachetool parameter in my `host` definition:

    ->set('cachetool', '/var/run/php7.2-fpm-shop.tld.sock')

Seems to work.
