### ISSUE TITLE
Fix packagist version

### ISSUE THREAD

**Issue by rikwillems** [jalogut/magento2-deployer-plus#35]
Hi, packagist.org still shows 2.3.0 as the most recent version. Can you please fix this?

**Comment by jalogut** [comment]
Hi, I just checked it and it seems to be ok now. Maybe there was a packagist problem at some point?

<img width="1440" alt="Screenshot 2019-05-17 at 12 28 06" src="https://user-images.githubusercontent.com/6410900/57922141-57d1a100-789f-11e9-8071-59ff8bc21f64.png">
