### ISSUE TITLE
Exclude node_modules from artifact

### ISSUE THREAD

**Issue by rikwillems** [jalogut/magento2-deployer-plus#37]
My node_modules directory is +/- 160mb in size and it is included in the build artifact. Magento doesn't need this directory in production. Can we ignore it for the artifact?

**Comment by osrecio** [comment]
Hi @rikwillems 

You can override the variable: `artifact_excludes_file` in `deploy.php`

`set('artifact_excludes_file', '<magento_root>/path/to/artifact/');`

Example:

`set('artifact_excludes_file', __DIR__ . '/../../config/artifact.excludes');`

And add the folders or files that you want exclude.

Example of [artifact.excludes](https://github.com/jalogut/magento2-deployer-plus/blob/master/config/artifact.excludes)

**Comment by rikwillems** [comment]
Hi @osrecio that is true and found that in the code. Just wonder if it isn't relevant for all users.

**Comment by jalogut** [comment]
Hi @rikwillems 

Not sure if that is relevant for all users. That is not my case for example. Let's leave the issue open and see if other users upvote it. In there is someone else with the same problem, we could add it.
