### ISSUE TITLE
Exclude .DS_Store & ._.DS_Store from artifact

### ISSUE THREAD

**Issue by rikwillems** [jalogut/magento2-deployer-plus#38]
Creating artifacts on my MacOS system also brings .DS_Store & ._.DS_Store files to the server. These should be excluded when creating artifacts.

**Comment by erfanimani** [comment]
If you check out artifact.php, you'll see that the command that creates the artifact is

    task('artifact:package', 'tar --exclude-from={{artifact_excludes_file}} -czf {{artifact_path}} .');

with the artifact file being 

    set('artifact_excludes_file', __DIR__ . '/../../config/artifact.excludes');

I haven't tried it myself, but I would imagine that it should be enough to create that file and add your desired ignored files to it.

**Comment by rikwillems** [comment]
That is true but having sane defaults in `artifact.excludes` would benefit everybody.

**Comment by osrecio** [comment]
I will work on it to be added. Thanks @rikwillems
