### ISSUE TITLE
Compiling fails due to disabled modules

### ISSUE THREAD

**Issue by mage2go** [jalogut/magento2-deployer-plus#42]
I am encountering the following error when deploying:

`➤ Executing task files:compile
[production] > cd ~/magento2/releases/20191121160900 && (/usr/bin/php ./bin/magento setup:di:compile)
[production] < You cannot run this command because modules are not enabled. You can enable modules by running the 'module:enable --all' command.
➤ Executing task deploy:failed
`

Is there something i am missing here? I'm not sure why the modules are disabled in the first place..

**Comment by VivekShingala** [comment]
Hi @mage2go 

Could you please share how did you resolve it?

**Comment by VivekShingala** [comment]
Ok, we resolved it by untracking app/etc/config.php file from .gitingore. Basically, the file app/etc/config.php was missing.
