### ISSUE TITLE
Deployment fails with upgrade to symfony/console version 5

### ISSUE THREAD

**Issue by wilfriedwolf** [jalogut/magento2-deployer-plus#46]
With the upgrade to symfony/console from 4.1.11 to 4.1.12
magento2-deployer-plus will fail, because of the type declaration introduced there and the missing description in magento2-deployer-plus.
```
/**
     * Sets the description for the command.
     *
     * @return $this
     */
    public function setDescription(string $description)
    {
        $this->description = $description;
        return $this;
    }
```
I'll do a pull request in a while...

Best regards, 
Willi

**Comment by piotrkwiecinski** [comment]
It's related to: https://github.com/jalogut/magento2-deployer-plus/commit/f7e076244f85be354b87818ed9c846143f336b0b I believe.

**Comment by piotrkwiecinski** [comment]
Just in case if it's a blocker for anyone as a temporary workaround you can lock version of deployer in composer.json to:
`"deployer/dist": "<6.7"`

**Comment by wilfriedwolf** [comment]
Oh, ok. I thought, deployer would now require a description. I'll close the issue then..
