### ISSUE TITLE
Magento v2.3.3

### ISSUE THREAD

**Issue by thiagolima-bm** [jalogut/magento2-deployer-plus#47]
When running

`php vendor/bin/dep -n deploy develop`

PHP Fatal error: Declaration of Symfony\Component\Console\Input\Input::getArgument($name) must be compatible with Symfony\Component\Console\Input\InputInterface::getArgument(string $name) in phar:///opt/atlassian/pipelines/agent/build/vendor/deployer/dist/dep/vendor/symfony/console/Input/Input.php on line 28

**Comment by thiagolima-bm** [comment]
Hello there @osrecio!
Does the deployer support the version 2.3.3 of Magento?

**Comment by sprankhub** [comment]
Please check your version of `deployer/dist`. I think this issue is solved with the latest version 6.7.3.

**Comment by sergy-gzh** [comment]
Hi @thiagolima-bm !
Have you tried upgrading your php version to 7.2?
I had the same issue. Noticed that `deployer` doesn't support php lower than 7.2 anymore.
https://github.com/deployphp/deployer/blob/master/composer.json
So its possible that package you have installed is a bit out of date.

**Comment by osrecio** [comment]
Thanks both of you guys @sprankhub @sergy-gzh .
