### ISSUE TITLE
How to add your production env.php in the artifact

### ISSUE THREAD

**Issue by grll** [jalogut/magento2-deployer-plus#48]
Hi I am trying to use your build artifacts deploy recipe. 

1) Building step goes fine.

2) Sending and deploying: 
- When sending to my production server I have trouble understanding how to specify my production "env.php" file.  Obviously my artifact archive don't contain my local "env.php" (as it would put my local env on my production server) but when deploying on my production server `bin/magento setup:upgrade` can't be run and gives me error because the `env.php` production file is not there.

How do you set or specify the production `env.php` that must be use on the production server ?

**Comment by dareenzo** [comment]
Deployer has the concept of [shared_files](https://deployer.org/docs/configuration.html#shared_files), which is just a list of files that are to be shared between deployments. These shared files will exist in the shared `"deploy path"/shared` on your server.
This formula lists [`app/etc/env.php`](https://github.com/jalogut/magento2-deployer-plus/blob/267c2afaa8f7a012ce4c08c35a9f64aa58ed4f12/recipe/magento_2_1.php#L32-L34) as one of them.

So what you want to do is to go to your server and replace the blank `"deploy path"/shared/app/etc/env.php` file with yours.

The file that exists in `"deploy path"/current/app/etc/env.php` is a symlink to the file mentioned above

Upon each the deployment a symlink to the shared file is created.

**Comment by grll** [comment]
I see thanks, for the highlight I will dig into that

**Comment by osrecio** [comment]
Thanks @dareenzo :D 

Closing this issue
