### ISSUE TITLE
Artifact symlinks and deploy mode

### ISSUE THREAD

**Issue by stu177** [jalogut/magento2-deployer-plus#50]
Something I've noticed when building an artifact locally is if you're in developer mode, the artifact is built using the symlinks of your local environment. This casuses broken symlinks to be pushed to the remote.

I've been doing this to get around this issue:

````php
// Put into production mode for artifact generation
task('mode:production', '{{bin/php}} {{current_path}}/{{magento_bin}} deploy:mode:set production -s')->once();
before('deploy:vendors', 'mode:production');

// Back to developer mode after artifact generation
task('mode:developer', '{{bin/php}} {{current_path}}/{{magento_bin}} deploy:mode:set developer -s')->once();
after('artifact:package', 'mode:developer');
````

Symlinks are set by the value for `view_preprocessed` in `app/etc/di.xml`:

````xml
<virtualType name="developerMaterialization" type="Magento\Framework\App\View\Asset\MaterializationStrategy\Factory">
    <arguments>
        <argument name="strategiesList" xsi:type="array">
            <item name="view_preprocessed" xsi:type="object">Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink</item>
            <item name="default" xsi:type="object">Magento\Framework\App\View\Asset\MaterializationStrategy\Copy</item>
        </argument>
    </arguments>
</virtualType>
````

Which causes files in `pub/static/adminhtml/Magento/backend/en_GB` to be symlinks. I'm guessing symlinks are used in other places but this was the main issue for as it was breaking assets for the admin area.

Not sure if anyone else has had this issue and have any other solutions?

**Comment by Morgy93** [comment]
Same issue here since the last `composer update`
It COULD be due to one of these updates:
```
  - Updating doctrine/annotations (v1.8.0 => 1.10.1)
  - Updating google/recaptcha (1.2.3 => 1.2.4)
  - Updating mage2tv/magento-cache-clean (1.0.24 => 1.0.26)
  - Updating symfony/config (v4.4.5 => v4.4.7)
  - Updating symfony/css-selector (v4.4.5 => v4.4.7)
  - Updating symfony/dependency-injection (v4.4.5 => v4.4.7)
  - Updating symfony/options-resolver (v4.4.5 => v4.4.7)
  - Updating symfony/polyfill-util (v1.14.0 => v1.15.0)
  - Updating symfony/polyfill-php56 (v1.14.0 => v1.15.0)
  - Updating symfony/inflector (v5.0.5 => v5.0.7)
  - Updating symfony/property-access (v5.0.5 => v5.0.7)
  - Updating symfony/dom-crawler (v4.4.5 => v4.4.7)
  - Updating symfony/browser-kit (v4.4.5 => v4.4.7)
  - Updating symfony/polyfill-php72 (v1.14.0 => v1.15.0)
  - Updating symfony/polyfill-intl-idn (v1.14.0 => v1.15.0)
  - Updating symfony/mime (v5.0.5 => v5.0.7)
  - Updating symfony/http-foundation (v5.0.5 => v5.0.7)
  - Updating symfony/polyfill-php70 (v1.14.0 => v1.15.0)
  - Updating symfony/stopwatch (v4.4.5 => v4.4.7)
  - Updating symfony/yaml (v4.4.5 => v4.4.7)
  - Updating vlucas/phpdotenv (v2.6.1 => v2.6.2)
```
But it could as well be totally false leading.. 😁

**Comment by dareenzo** [comment]
I used to have these too. In fact its not this packages fault. It is just how Magento works. In developer mode it uses symlinks for static assets. So if you create an artifact while in developer mode, when the package is "untared" elsewhere it will have invalid symlinks. The solution is just something in the lines of what the OP posted: get your site in production before deploy-artifacts.

**Comment by osrecio** [comment]
Thanks @dareenzo.

@stu177 you should have your local copy in production mode. 

I recommend that you have a separate folder that is a copy of your project and that it is in production mode. 

This way you will deploy from your new folder.
