### ISSUE TITLE
Do you plan to fix crontab:update command?

### ISSUE THREAD

**Issue by Maksold** [jalogut/magento2-deployer-plus#55]
@jalogut In this commit https://github.com/jalogut/magento2-deployer-plus/commit/b4c49604ce7830e6c11cc56f4447331622c0d782#diff-208cd8f19512e36ea5e04343f5d39c1d you disabled crontab:update command. Do you plan to fix it or may be you have ideas how to do it?

**Comment by osrecio** [comment]
No plan to be fixed.

If you want to have the availability you can have in your deploy.php something like this:

```
task('magento:cron:update', function () {
    //magic stuff
});

after('deploy:override_shared', 'magento:cron:update');
```

**Comment by Maksold** [comment]
Thanks, @osrecio!
