### ISSUE TITLE
Update On packagist.org

### ISSUE THREAD

**Issue by sprankhub** [jalogut/magento2-deployer-plus#57]
Could you please manually update the package on packagist.org? It still shows 2.6.0 as the latest version:

![image](https://user-images.githubusercontent.com/930199/79559079-6c1cb000-80a5-11ea-9bfe-46c67b6c630d.png)

Additionally, it would make sense to [configure auto-updates](https://packagist.org/about#how-to-update-packages).

**Comment by osrecio** [comment]
I can’t the only one can do is @jalogut 

I will try to speak with him asap

**Comment by osrecio** [comment]
@sprankhub solved: https://packagist.org/packages/jalogut/magento2-deployer-plus

Now I’m maintainer in packagist and I will add the autoupdate

Thanks!
