### ISSUE TITLE
Failed opening required 'recipe/common.php' 

### ISSUE THREAD

**Issue by rikwillems** [jalogut/magento2-deployer-plus#75]
Using docker image `markoshust/magento-php:7.4-fpm` I'm getting this error.

`Fatal error: require(): Failed opening required 'recipe/common.php' (include_path='phar:///data/vendor/deployer/dist/dep/bin/../:.:/usr/local/lib/php') in /data/vendor/jalogut/magento2-deployer-plus/recipe/magento_2_2_5.php on line 13`

The fix is to change `require` to `require_once`, also for files `magento_2_2.php` and `magento_2_1.php`.

Try:
`docker run  --volume ${PWD}:/data --workdir /data -it markoshust/magento-php:7.4-fpm vendor/bin/dep build -vvv`

**Comment by VivekShingala** [comment]
The error is occurred because recipe/common.php file not present.
